### ISSUE TITLE
🐛 BUG: Unexpected behaviour when applying scoped styling to `html` and `body` tags in a `layout.astro` component

### ISSUE THREAD

**Issue by markteekman** [snowpackjs/astro#1074]
### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I've got a `DefaultLayout.astro` with some scoped styles and this is what I'm setting:

```css
html,
body {
  height: 100%;
}
```

This results in the following CSS rendered in the browser:

```css
html,
body.astro-zvkshqHn {
  height: 100%;
}
```

The body doesn't get that class so the `height: 100%` is not applied.

### Steps to Reproduce

1. `npm start`
2. Set scoped classes in `DefaultLayout.astro`
3. Body class added to rendered CSS
4. Body class NOT added in rendered HTML
