### ISSUE TITLE
🐛 BUG: `*` inside `calc()` in component CSS resolves to a class name in v0.21.0

### ISSUE THREAD

**Issue by myakura** [snowpackjs/astro#1942]
### What version of `astro` are you using?

v0.21.0

### What package manager are you using?

npm

### What operating system are you using?

Windows (WSL2 Ubuntu)

### Describe the Bug

I use CSS `calc()` inside a component to multiply values:

```css
header {
  background-color: #111;
  color: #fff;
  padding: var(--space) calc(var(--space) * 2);
}
``` 

I just migrated to v0.21.0 and saw the padding does not apply to the header. So I went into DevTools to inspect the element and I saw the compiled code was broken:

```css
header.astro-HCIMERBM{background-color:#111;color:#fff;padding:var(--space) calc(var(--space) .astro-HCIMERBM 2)}
```

Take a close look at `calc()`, the `*` is transformed to `.astro-HCIMERBM`, which the same as the class name applied to the header.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-u7subm-lpxxer?file=src/pages/index.astro
