### ISSUE TITLE
🐛 BUG: Nested CSS syntax in Svelte components triggers an error

### ISSUE THREAD

**Issue by oliverturner** [snowpackjs/astro#1950]
### What version of `astro` are you using?

0.21

### What package manager are you using?

npm

### What operating system are you using?

Mac OS

### Describe the Bug

Using nested media queries with SCSS syntax in Svelte components causes Astro to return a 500

```scss 
<style lang="scss">
  .counter {
    display: grid;
    place-items: center;
    grid-template-columns: repeat(3, minmax(0, 1fr));

    font-size: 2em;
    margin-top: 2em;

    @media (min-width: 768px) {
      background: hotpink; // Identifier is expected: svelte(css-syntax-error)
    }
  }
}
```

### Link to Minimal Reproducible Example

https://codesandbox.io/s/hardcore-keller-tllgj?file=/src/components/Counter.svelte
