### ISSUE TITLE
🐛 BUG: Asterisk wrongly replaced in CSS

### ISSUE THREAD

**Issue by waspeer** [snowpackjs/astro#1965]
### What version of `astro` are you using?

0.21.0

### What package manager are you using?

pnpm/npm

### What operating system are you using?

mac

### Describe the Bug

When using an asterisk (eg in a style calc function) it gets replaced with a astro scoped class.

So this:

```css
h1 {
  /* ... */
  animation-delay: calc(2 * 1s);
}
```

Renders as this:

```css
h1 {
  /* ... */
  animation-delay: calc(2 .astro-T53Z2D3J 1s);
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hmth3w?file=src/pages/index.astro
