### ISSUE TITLE
🐛 BUG: Using Astro-0.18.0-next.5 with Github Actions fails

### ISSUE THREAD

**Issue by JSHSJ** [snowpackjs/astro#854]
### What package manager are you using?

pnpm / npm

### What operating system are you using?

Linux

### Describe the Bug

When trying to run build, Astro fails with the following exception:
```

node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: ENOENT: no such file or directory, open '/home/runner/work/{repoName}/node_modules/.cache/snowpack/build/astro@0.18.0-next.5/astro/dist/internal/h.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/runner/work/{repoName}/node_modules/.cache/snowpack/build/astro@0.18.0-next.5/astro/dist/internal/h.js'
}
 ERROR  Command failed with exit code 1.
```

Using the same setup (Node 16, pnpm) works just fine.

I feel like this error is more on snowpack or me.

### Steps to Reproduce

- Install Astro using astro@next (v.0.18.0-next.5)
- Create a github actions yaml file with these contents:

```
name: Build and deploy
on:
  push:
    branches: [master]
  workflow_dispatch:


jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    strategy:     
      matrix:        
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
            node-version: ${{ matrix.node-version }}
      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with: 
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.7.js | node - add --global pnpm@6
      - run: pnpm install
      - run: pnpm build
```

Edit: 

Same issue using npm and this actions.yml

```
name: Build and deploy
on:
  push:
    branches: [master]
  workflow_dispatch:


jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    strategy:     
      matrix:        
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
            node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Build
        run: |
          npm run build
          touch ./dist/.nojekyll
```
